In [14]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import string

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


#Visualizations library
import seaborn as sns 
import matplotlib.pyplot as plt


#Stats library
from scipy import stats
from scipy.stats import norm, skew 

#Preprocessing Libraries
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from scipy.special import boxcox1p
from sklearn.feature_extraction.text import CountVectorizer


# Modellling Librries
from sklearn.linear_model import ElasticNet, Lasso,  BayesianRidge, LassoLarsIC, LassoCV, Ridge, LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler, LabelEncoder
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn.model_selection import GridSearchCV 

import os
# print(os.listdir("../House Price Predictor"))

# Any results you write to the current directory are saved as output.

In [4]:
sales = pd.read_csv('kc_house_data.csv')

In [5]:
trainData = pd.read_csv('kc_house_train_data.csv')
testData = pd.read_csv('kc_house_test_data.csv')

In [7]:
for df in  [trainData, testData]:
    df['bedrooms_squared'] = df['bedrooms'] * df['bedrooms']
    df['bed_bath_rooms'] = df['bedrooms'] * df['bathrooms']
    df['log_sqft_living'] = np.log(df['sqft_living'])
    df['lat_plus_long'] = df['lat'] + df['long']

In [8]:
trainData

id             date      price  bedrooms  bathrooms  \
0      7129300520  20141013T000000   221900.0         3       1.00   
1      6414100192  20141209T000000   538000.0         3       2.25   
2      5631500400  20150225T000000   180000.0         2       1.00   
3      2487200875  20141209T000000   604000.0         4       3.00   
4      1954400510  20150218T000000   510000.0         3       2.00   
5      7237550310  20140512T000000  1225000.0         4       4.50   
6      1321400060  20140627T000000   257500.0         3       2.25   
7      2008000270  20150115T000000   291850.0         3       1.50   
8      2414600126  20150415T000000   229500.0         3       1.00   
9      3793500160  20150312T000000   323000.0         3       2.50   
10     1736800520  20150403T000000   662500.0         3       2.50   
11     9212900260  20140527T000000   468000.0         2       1.00   
12     6054650070  20141007T000000   400000.0         3       1.75   
13     1175000570  20150312T000000   530000.0         5       2.00   
14     1875500060  20140731T000000   395000.0         3       2.00   
15     6865200140  20140529T000000   485000.0         4       1.00   
16       16000397  20141205T000000   189000.0         2       1.00   
17     7983200060  20150424T000000   230000.0         3       1.00   
18     6300500875  20140514T000000   385000.0         4       1.75   
19     2524049179  20140826T000000  2000000.0         3       2.75   
20     7137970340  20140703T000000   285000.0         5       2.50   
21     8091400200  20140516T000000   252700.0         2       1.50   
22     3814700200  20141120T000000   329000.0         3       2.25   
23     1794500383  20140626T000000   937000.0         3       1.75   
24     3303700376  20141201T000000   667000.0         3       1.00   
25     5101402488  20140624T000000   438000.0         3       1.75   
26     1873100390  20150302T000000   719000.0         4       2.50   
27     2426039314  20141201T000000   280000.0         2       1.50   
28      461000390  20140624T000000   687500.0         4       1.75   
29     7955080270  20141203T000000   322500.0         4       2.75   
...           ...              ...        ...       ...        ...   
17354  1931300090  20140507T000000   610950.0         3       3.00   
17355  9253900271  20150107T000000  3567000.0         5       4.50   
17356   567000385  20140623T000000   362500.0         2       1.50   
17357  7011201004  20140529T000000   645000.0         3       3.25   
17358  7853420110  20141003T000000   594866.0         3       3.00   
17359  7853420110  20150504T000000   625000.0         3       3.00   
17360   952006823  20141202T000000   380000.0         3       2.50   
17361  3832050760  20140828T000000   270000.0         3       2.50   
17362  2767604724  20141015T000000   505000.0         2       2.50   
17363  6632300207  20150305T000000   385000.0         3       2.50   
17364  2767600688  20141113T000000   414500.0         2       1.50   
17365  7570050450  20140910T000000   347500.0         3       2.50   
17366  7430200100  20140514T000000  1222500.0         4       3.50   
17367  4140940150  20141002T000000   572000.0         4       2.75   
17368  1931300412  20150416T000000   475000.0         3       2.25   
17369  1972201967  20141031T000000   520000.0         2       2.25   
17370  7502800100  20140813T000000   679950.0         5       2.75   
17371   191100405  20150421T000000  1575000.0         4       3.25   
17372  8956200760  20141013T000000   541800.0         4       2.50   
17373  7202300110  20140915T000000   810000.0         4       3.00   
17374   249000205  20141015T000000  1537000.0         5       3.75   
17375  5100403806  20150407T000000   467000.0         3       2.50   
17376   844000965  20140626T000000   224000.0         3       1.75   
17377  7852140040  20140825T000000   507250.0         3       2.50   
17378  9834201367  20150126T000000   429000.0         3       2.00   
17379  7936000429  201503

In [13]:
meanVal = []
for feat in ['bedrooms_squared', 'bed_bath_rooms', 'log_sqft_living', 'lat_plus_long']:
    meanVal.append(testData[feat].mean())
    
print(meanVal)

[12.4466777015843, 7.5039016315913925, 7.550274679645921, -74.65333355403185]


In [15]:
model1 = LinearRegression()
model2 = LinearRegression()
model3 = LinearRegression()

In [22]:
feats1 = ['sqft_living', 'bedrooms', 'bathrooms', 'lat', 'long']
feats2 = feats1 + ['bed_bath_rooms']
feats3 = feats2 + ['bedrooms_squared', 'log_sqft_living', 'lat_plus_long']

In [18]:
model1.fit(trainData[feats1], trainData['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
model2.fit(trainData[feats2], trainData['price'])
model3.fit(trainData[feats3], trainData['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
model1.coef_

array([ 3.12258646e+02, -5.95865332e+04,  1.57067421e+04,  6.58619264e+05,
       -3.09374351e+05])

In [24]:
model2.coef_

array([ 3.06610053e+02, -1.13446368e+05, -7.14613083e+04,  6.54844630e+05,
       -2.94298969e+05,  2.55796520e+04])

In [25]:
model3.coef_

array([ 5.29422820e+02,  3.45142296e+04,  6.70607813e+04,  5.34085611e+05,
       -4.06750711e+05, -8.57050439e+03, -6.78858667e+03, -5.61831484e+05,
        1.27334900e+05])

In [29]:
output = testData.price

In [30]:
testData.drop('price', axis=1, inplace=True)

In [27]:
def getRSS(output, predictions):
    RSS = np.sum(np.square(output-predictions))
    return RSS

In [33]:
predict1 = model1.predict(testData[feats1])
predict2 = model2.predict(testData[feats2])
predict3 = model3.predict(testData[feats3])

In [50]:
predictTr1 = model1.predict(trainData[feats1])
predictTr2 = model2.predict(trainData[feats2])
predictTr3 = model3.predict(trainData[feats3])

In [47]:
RSSVal = []
for pred in [predict1, predict2, predict3]:
    RSSVal.append(getRSS(output, pred))

In [48]:
RSSVal

[225500469795490.34, 223377462976467.5, 259236319207180.12]

In [52]:
outputTr = trainData.price

In [53]:
RSSValTr = []
for pred in [predictTr1, predictTr2, predictTr3]:
    RSSValTr.append(getRSS(outputTr, pred))

In [54]:
RSSValTr

[967879963049545.8, 958419635074070.0, 903436455050477.8]